class DatabaseAuthException(Exception):
    """Raised when trying to access database with a faulty identificator"""